import { OsiLayer, TcpIpLayer } from "@/types";

export const OSI_LAYERS: OsiLayer[] = [
  {
    number: 7,
    id: "application",
    nameKo: "응용 계층",
    nameEn: "Application Layer",
    pdu: "Data (메시지)",
    color: "#EF4444",
    badgeBg: "bg-red-500/15",
    badgeBorder: "border-red-500/30",
    badgeText: "text-red-400",
    summary: "사용자가 사용하는 프로그램(웹 브라우저, 이메일 등)과 네트워크 간의 인터페이스를 제공합니다.",
    metaphor: "📬 [편지 내용 작성] 친구에게 보낼 편지지에 글을 적는 단계입니다.",
    functions: [
      "사용자 인터페이스 및 네트워크 서비스 제공",
      "웹 브라우징(HTTP/HTTPS), 파일 전송(FTP), 이메일(SMTP) 등의 응용 프로토콜 처리",
      "클라이언트-서버 간 요청/응답 형식 정의",
    ],
    protocols: ["HTTP", "HTTPS", "DNS", "WebSocket", "SSH", "FTP", "SMTP", "DHCP"],
    hardware: ["웹 브라우저", "API 서버", "L7 로드밸런서(ALB)", "WAF(웹 방화벽)"],
    headerName: "Application Data",
    headerFields: [
      { label: "Request Method", example: "GET /index.html HTTP/1.1", desc: "요청 메서드 및 URI" },
      { label: "Headers", example: "Host: example.com, User-Agent: Chrome", desc: "클라이언트 메타데이터" },
      { label: "Body", example: "{\"message\": \"Hello\"}", desc: "전송할 실제 데이터 본문" },
    ],
    developerTip: "💡 프론트엔드 개발자가 fetch()나 axios로 요청을 보낼 때 직접 다루는 영역입니다.",
  },
  {
    number: 6,
    id: "presentation",
    nameKo: "표현 계층",
    nameEn: "Presentation Layer",
    pdu: "Data (표현 데이터)",
    color: "#F97316",
    badgeBg: "bg-orange-500/15",
    badgeBorder: "border-orange-500/30",
    badgeText: "text-orange-400",
    summary: "데이터를 서로 이해할 수 있는 공통 형식으로 변환(인코딩/디코딩), 암호화(TLS), 압축합니다.",
    metaphor: "🔐 [암호화 및 번역] 편지 내용을 상대방이 읽을 수 있는 언어로 번역하고 비밀 암호로 잠그는 단계입니다.",
    functions: [
      "데이터 인코딩/디코딩 (UTF-8, ASCII, Base64 등)",
      "데이터 암호화/복호화 (SSL/TLS, HTTPS 보안)",
      "데이터 압축/압축해제 (Gzip, Brotli 등)",
    ],
    protocols: ["TLS/SSL", "JPEG", "PNG", "MIME", "JSON/XML Serialization"],
    hardware: ["TLS 가속기", "암호화 모듈"],
    headerName: "Presentation Data",
    headerFields: [
      { label: "Content-Type", example: "application/json; charset=utf-8", desc: "데이터 인코딩 및 형식" },
      { label: "Content-Encoding", example: "gzip", desc: "압축 알고리즘" },
      { label: "Encryption State", example: "TLS 1.3 Cipher Suite", desc: "암호화 적용 상태" },
    ],
    developerTip: "💡 JSON.stringify()나 HTTPS(TLS 핸드셰이크)가 이 계층에 해당합니다.",
  },
  {
    number: 5,
    id: "session",
    nameKo: "세션 계층",
    nameEn: "Session Layer",
    pdu: "Data (세션 데이터)",
    color: "#F59E0B",
    badgeBg: "bg-amber-500/15",
    badgeBorder: "border-amber-500/30",
    badgeText: "text-amber-400",
    summary: "통신 장치 간의 연결 설정, 유지, 동기화 및 세션 종료를 관리합니다.",
    metaphor: "🤝 [통화 연결 및 신원 확인] 전화를 걸어 '여보세요? 들리시나요?' 하고 대화 상태를 유지하는 단계입니다.",
    functions: [
      "통신 세션 생성, 유지 및 정상 종료 관리",
      "동기점(Checkpoint) 설정을 통한 전송 실패 시 복구",
      "동시 송수신(전이중) 또는 번갈아 송수신(반이중) 제어",
    ],
    protocols: ["NetBIOS", "RPC", "PPTP", "SOCKS5", "gRPC Sessions"],
    hardware: ["게이트웨이", "세션 관리자"],
    headerName: "Session Token",
    headerFields: [
      { label: "Session ID", example: "sess_99a8b7c6", desc: "통신 식별자" },
      { label: "Sync Points", example: "CheckPoint #4", desc: "오류 복구를 위한 동기화 지점" },
      { label: "State", example: "ESTABLISHED", desc: "세션 연결 상태" },
    ],
    developerTip: "💡 웹소켓 연결 유지(Ping/Pong)나 RPC 원격 프로시저 호출 세션 관리에 쓰입니다.",
  },
  {
    number: 4,
    id: "transport",
    nameKo: "전송 계층",
    nameEn: "Transport Layer",
    pdu: "Segment (TCP) / Datagram (UDP)",
    color: "#10B981",
    badgeBg: "bg-emerald-500/15",
    badgeBorder: "border-emerald-500/30",
    badgeText: "text-emerald-400",
    summary: "송신자와 수신자 간의 신뢰성 있는 데이터 전송과 포트(Port) 번호를 통한 프로세스 식별을 담당합니다.",
    metaphor: "📦 [택배 상자 포장 & 등기 배송] 편지를 상자에 넣고 어느 방(포트 번호)으로 갈지 적으며, 수령 확인증을 요청하는 단계입니다.",
    functions: [
      "포트(Port) 번호를 이용한 서비스/프로세스 식별 (예: 80, 443, 3000)",
      "신뢰성 보장 및 흐름/혼잡 제어 (TCP의 3-Way Handshake, 재전송)",
      "비연결성 고속 전송 (UDP의 실시간 스트리밍)",
      "데이터 분할(Segmentation) 및 재조립",
    ],
    protocols: ["TCP", "UDP", "QUIC", "SCTP"],
    hardware: ["L4 스위치 (로드밸런서)", "포트 기반 방화벽"],
    headerName: "TCP/UDP Header",
    headerFields: [
      { label: "Source Port", example: "52140", desc: "클라이언트의 임시 포트 번호" },
      { label: "Dest Port", example: "443 (HTTPS)", desc: "도착지 서버 프로세스 포트" },
      { label: "Seq / Ack Number", example: "Seq=1001, Ack=1", desc: "순서 번호 및 수신 확인 번호 (TCP)" },
      { label: "Flags", example: "SYN, ACK, FIN, PSH", desc: "연결 제어 플래그" },
      { label: "Checksum", example: "0x8E12", desc: "오류 검출 코드" },
    ],
    developerTip: "💡 localhost:3000에서 '3000'이 바로 이 전송 계층의 포트(Port) 번호입니다!",
  },
  {
    number: 3,
    id: "network",
    nameKo: "네트워크 계층",
    nameEn: "Network Layer",
    pdu: "Packet (패킷)",
    color: "#06B6D4",
    badgeBg: "bg-cyan-500/15",
    badgeBorder: "border-cyan-500/30",
    badgeText: "text-cyan-400",
    summary: "논리적 주소(IP)를 기반으로 전 세계 네트워크 간의 최적 경로(라우팅)를 찾아 패킷을 전달합니다.",
    metaphor: "🗺️ [내비게이션 & 우편 주소] 도로명 주소(IP 주소)를 보고 최적의 고속도로 경로를 찾아 배송차를 출발시키는 단계입니다.",
    functions: [
      "논리적 주소 지정 (IPv4 / IPv6 주소 체계)",
      "최적 경로 탐색 및 패킷 전달 (라우팅, Routing)",
      "패킷 단편화 및 조립",
      "네트워크 진단 및 오류 보고 (ICMP Ping)",
    ],
    protocols: ["IPv4", "IPv6", "ICMP (Ping)", "IPsec", "ARP", "BGP", "OSPF"],
    hardware: ["라우터(Router)", "L3 스위치", "공유기(NAT 라우터)"],
    headerName: "IP Header",
    headerFields: [
      { label: "Source IP", example: "192.168.1.100", desc: "출발지 컴퓨터의 IP 주소" },
      { label: "Destination IP", example: "142.250.196.110 (Google)", desc: "최종 목적지 서버의 IP 주소" },
      { label: "TTL (Time to Live)", example: "64", desc: "패킷이 거칠 수 있는 최대 홉(Hop) 수" },
      { label: "Protocol", example: "6 (TCP) / 17 (UDP)", desc: "상위 계층 프로토콜 번호" },
    ],
    developerTip: "💡 ping google.com 명령어나 클라우드 VPC/서브넷 설정이 이 계층에 속합니다.",
  },
  {
    number: 2,
    id: "data-link",
    nameKo: "데이터 링크 계층",
    nameEn: "Data Link Layer",
    pdu: "Frame (프레임)",
    color: "#3B82F6",
    badgeBg: "bg-blue-500/15",
    badgeBorder: "border-blue-500/30",
    badgeText: "text-blue-400",
    summary: "동일한 물리적 네트워크(LAN) 내에서 물리적 주소(MAC)를 이용해 기기 간의 안전한 프레임 전송을 담당합니다.",
    metaphor: "🚚 [동네 택배 배송차] 택배 기사님이 아파트 동/호수(MAC 주소)를 확인하고 직접 문 앞까지 전달하는 단계입니다.",
    functions: [
      "물리적 주소 지정 (48비트 MAC 주소)",
      "데이터를 프레임 단위로 묶고 헤더/트레일러 부착",
      "오류 검출 및 폐기 (CRC / FCS 체크섬)",
      "매체 접근 제어 (CSMA/CD, Wi-Fi 802.11)",
    ],
    protocols: ["Ethernet (이더넷)", "Wi-Fi (802.11)", "PPP", "ARP", "VLAN (802.1Q)"],
    hardware: ["스위치(L2 Switch)", "네트워크 카드(NIC)", "브리지"],
    headerName: "Ethernet Header & Trailer",
    headerFields: [
      { label: "Source MAC", example: "00:1A:2B:3C:4D:5E", desc: "송신 장비의 고유 하드웨어 MAC 주소" },
      { label: "Dest MAC", example: "AA:BB:CC:DD:EE:FF", desc: "다음 홉 장비(스위치/게이트웨이)의 MAC 주소" },
      { label: "EtherType", example: "0x0800 (IPv4)", desc: "상위 계층 프로토콜 타입" },
      { label: "FCS / CRC (Trailer)", example: "0x3F2A81", desc: "전송 중 비트 손상 여부를 검증하는 트레일러" },
    ],
    developerTip: "💡 공유기 LAN 포트에 꽂히는 랜선 및 유무선 공유기 내부 스위칭의 핵심 계층입니다.",
  },
  {
    number: 1,
    id: "physical",
    nameKo: "물리 계층",
    nameEn: "Physical Layer",
    pdu: "Bits (0과 1의 전기/광 신호)",
    color: "#8B5CF6",
    badgeBg: "bg-purple-500/15",
    badgeBorder: "border-purple-500/30",
    badgeText: "text-purple-400",
    summary: "데이터를 0과 1의 전기 신호, 빛, 또는 무선 주파수 신호로 변환하여 실제 물리적 전송 매체로 흘려보냅니다.",
    metaphor: "⚡ [구리선 & 광섬유 고속도로] 전깃줄이나 공기 중 전파를 통해 '삐-빅-삐' 0과 1의 펄스를 빠르게 쏘아 보내는 단계입니다.",
    functions: [
      "디지털 비트열(0101)을 아날로그 신호(전압, 광펄스, 전파)로 변환",
      "물리적 케이블 규격 및 커넥터 핀 배열 정의 (RJ45, 광섬유 등)",
      "전송 속도, 비트 동기화, 신호 증폭",
    ],
    protocols: ["1000BASE-T (Gigabit Ethernet)", "DSL", "USB", "Bluetooth Physical", "802.11 Phy"],
    hardware: ["랜선(UTP 케이블)", "광케이블", "허브(Hub)", "리피터(Repeater)", "트랜시버"],
    headerName: "Physical Signal (010101...)",
    headerFields: [
      { label: "Preamble", example: "10101010 10101011 (SFD)", desc: "수신측 클럭 동기화를 위한 시작 비트 패턴" },
      { label: "Signal Encoding", example: "Manchester / 4B5B / PAM-5", desc: "전압 레벨 및 신호 변조 방식" },
      { label: "Bitstream", example: "01001000 01100101...", desc: "실제 전송되는 2진수 전기/광 펄스" },
    ],
    developerTip: "💡 랜선이 빠졌거나 와이파이 안테나가 불량일 때 발생하는 문제가 1계층 문제입니다.",
  },
];

export const TCPIP_LAYERS: TcpIpLayer[] = [
  {
    number: 4,
    id: "tcp-application",
    nameKo: "응용 계층 (Application)",
    nameEn: "Application Layer",
    osiLayerNumbers: [7, 6, 5],
    pdu: "Data (메시지)",
    protocols: ["HTTP", "HTTPS", "DNS", "SSH", "FTP", "WebSocket", "TLS"],
    description: "OSI의 응용(7), 표현(6), 세션(5) 계층을 하나로 통합한 계층입니다. 실제 웹 서비스 및 소프트웨어 애플리케이션의 프로토콜을 다룹니다.",
    color: "#EF4444",
  },
  {
    number: 3,
    id: "tcp-transport",
    nameKo: "전송 계층 (Transport)",
    nameEn: "Transport Layer",
    osiLayerNumbers: [4],
    pdu: "Segment / Datagram",
    protocols: ["TCP", "UDP", "QUIC"],
    description: "OSI 전송(4) 계층과 1:1로 매핑됩니다. 포트 번호를 기반으로 프로세스 간의 신뢰성 있거나 신속한 데이터 교환을 담당합니다.",
    color: "#10B981",
  },
  {
    number: 2,
    id: "tcp-internet",
    nameKo: "인터넷 계층 (Internet)",
    nameEn: "Internet Layer",
    osiLayerNumbers: [3],
    pdu: "Packet (패킷)",
    protocols: ["IP (IPv4/IPv6)", "ICMP", "ARP", "IPsec"],
    description: "OSI 네트워크(3) 계층과 1:1로 매핑됩니다. IP 주소를 통해 전 세계 수많은 라우터를 거쳐 목적지까지 패킷을 라우팅합니다.",
    color: "#06B6D4",
  },
  {
    number: 1,
    id: "tcp-network-access",
    nameKo: "네트워크 접근 계층 (Network Access / Link)",
    nameEn: "Network Access Layer",
    osiLayerNumbers: [2, 1],
    pdu: "Frame & Bits",
    protocols: ["Ethernet", "Wi-Fi (802.11)", "PPP", "MAC / PHY"],
    description: "OSI 데이터링크(2)와 물리(1) 계층을 합친 계층입니다. 실제 하드웨어 NIC, 스위치, 랜선을 통해 비트를 프레임 단위로 인접 기기에 전송합니다.",
    color: "#3B82F6",
  },
];
