import { Protocol } from "@/types";

export const PROTOCOLS_LIST: Protocol[] = [
  {
    id: "http",
    name: "HTTP",
    fullName: "HyperText Transfer Protocol",
    layer: 7,
    defaultPort: "80",
    transport: "TCP",
    rfc: "RFC 9110 / RFC 9112",
    descriptionKo: "웹 브라우저와 웹 서버 간에 HTML, CSS, JavaScript, 이미지 등의 웹 리소스를 주고받기 위한 기본 프로토콜입니다.",
    keyPoints: [
      "Stateless(무상태성): 각 요청은 독립적이며 이전 요청의 상태를 기억하지 않음 (쿠키/세션/토큰으로 보완)",
      "Connectionless(비연결성): 요청-응답 후 연결을 끊는 원칙 (Keep-Alive로 재사용 가능)",
      "평문(Plaintext) 전송으로 인해 중간자 공격(Sniffing)에 취약함",
    ],
    useCases: ["일반 웹 서핑 및 웹 문서 조회", "내부망 REST API 통신", "캐싱 프록시"],
    alternatives: ["HTTPS (암호화 버전)", "HTTP/2 (다중화)", "HTTP/3 (QUIC 기반)"],
    importanceKo: "웹 개발자가 매일 사용하는 가장 기초적이고 중요한 응용 계층 통신 프로토콜입니다.",
  },
  {
    id: "https",
    name: "HTTPS",
    fullName: "HyperText Transfer Protocol Secure",
    layer: 7,
    defaultPort: "443",
    transport: "TCP",
    rfc: "RFC 2818",
    descriptionKo: "HTTP 통신에 SSL/TLS 암호화 계층을 추가하여 데이터의 도청, 변조, 위장을 방지하는 보안 웹 프로토콜입니다.",
    keyPoints: [
      "기밀성(보안 암호화): 제3자가 데이터를 가로채도 내용을 읽을 수 없음",
      "무결성: 전송 중 패킷이 위변조되지 않았음을 보장",
      "인증(CA 인증서): 접속한 서버가 진짜 신뢰할 수 있는 서버인지 확인",
    ],
    useCases: ["로그인, 결제 등 민감 정보를 다루는 모든 모던 웹사이트", "모바일 앱 백엔드 API", "OAuth2 인증"],
    alternatives: ["HTTP (보안 미적용)", "SSH (터널링)"],
    importanceKo: "오늘날 모든 상용 웹 서비스의 표준(Default)이며, 구글 검색 랭킹 및 브라우저 보안 경고의 필수 기준입니다.",
  },
  {
    id: "dns",
    name: "DNS",
    fullName: "Domain Name System",
    layer: 7,
    defaultPort: "53",
    transport: "Both",
    rfc: "RFC 1034 / RFC 1035",
    descriptionKo: "사람이 읽기 쉬운 도메인 이름(예: google.com)을 컴퓨터가 이해할 수 있는 IP 주소(예: 142.250.196.110)로 변환해 주는 인터넷의 전화번호부입니다.",
    keyPoints: [
      "일반 쿼리는 빠른 UDP 53번 포트를 주로 사용하며, 512바이트 초과 응답 및 Zone 전송 시 TCP 53번 사용",
      "계층적 분산 구조: Root DNS -> TLD DNS(.com) -> Authoritative DNS(google.com)",
      "DNS 캐싱(TTL)을 통해 빠른 응답 속도 제공",
    ],
    useCases: ["웹 브라우저에 URL 입력 시 IP 주소 탐색", "이메일 서버 MX 레코드 조회", "로드 밸런싱"],
    alternatives: ["hosts 파일 수동 등록", "DoH (DNS over HTTPS)", "DoT (DNS over TLS)"],
    importanceKo: "DNS가 멈추면 도메인을 사용하는 전 세계 모든 웹사이트에 접속할 수 없게 되는 필수 인프라입니다.",
  },
  {
    id: "websocket",
    name: "WebSocket",
    fullName: "WebSocket Protocol",
    layer: 7,
    defaultPort: "80 / 443",
    transport: "TCP",
    rfc: "RFC 6455",
    descriptionKo: "단일 TCP 연결 위에서 클라이언트와 서버 간에 실시간 양방향(전이중) 통신을 가능하게 하는 프로토콜입니다.",
    keyPoints: [
      "HTTP 핸드셰이크(Upgrade 헤더)로 연결을 시작한 뒤 영구적인 양방향 채널 유지",
      "매 요청마다 HTTP 헤더를 보낼 필요가 없어 오버헤드가 극히 적음 (프레임 단위 가벼운 전송)",
      "서버가 클라이언트에게 실시간으로 데이터를 푸시(Push) 가능",
    ],
    useCases: ["실시간 채팅 및 알림", "주식/코인 시세판", "멀티플레이어 웹 게임", "협업 캔버스 도구(Figma 등)"],
    alternatives: ["SSE (Server-Sent Events: 단방향)", "HTTP Polling / Long Polling", "WebRTC (P2P)"],
    importanceKo: "새로고침 없는 실시간 인터랙티브 웹 애플리케이션 구축의 핵심 기술입니다.",
  },
  {
    id: "tls",
    name: "TLS / SSL",
    fullName: "Transport Layer Security",
    layer: 6,
    defaultPort: "N/A (L6/L5)",
    transport: "TCP",
    rfc: "RFC 8446 (TLS 1.3)",
    descriptionKo: "인터넷 통신 보안을 위한 암호화 프로토콜로, 대칭키와 비대칭키 암호화를 조합하여 안전한 데이터 교환을 보장합니다.",
    keyPoints: [
      "TLS 1.3은 핸드셰이크를 1-RTT(또는 0-RTT)로 단축하여 극적인 속도 향상",
      "비대칭키(공개키)로 안전하게 비밀키를 교환한 뒤, 실제 데이터는 빠른 대칭키(AES-GCM 등)로 암호화",
      "SSL은 구버전 명칭이며 현재는 보안 결함으로 폐기되고 TLS가 사용됨",
    ],
    useCases: ["HTTPS 웹 보안", "SMTPS/IMAPS 메일 보안", "VPN 터널링", "데이터베이스 SSL 연결"],
    alternatives: ["IPsec (L3 암호화)", "SSH"],
    importanceKo: "데이터 도청을 원천 차단하고 무결성을 보장하는 현대 웹 보안의 핵심 기둥입니다.",
  },
  {
    id: "tcp",
    name: "TCP",
    fullName: "Transmission Control Protocol",
    layer: 4,
    defaultPort: "N/A (L4)",
    transport: "TCP",
    rfc: "RFC 9293",
    descriptionKo: "연결 지향적(Connection-oriented)이며, 데이터의 순서 보장, 유실 시 재전송, 혼잡 제어를 제공하는 신뢰성 중심의 전송 계층 프로토콜입니다.",
    keyPoints: [
      "3-Way Handshake (SYN -> SYN/ACK -> ACK)를 통한 안전한 연결 수립",
      "Sequence Number와 Acknowledgment Number로 패킷 누락 및 순서 꼬임 완벽 복구",
      "흐름 제어(Sliding Window) 및 혼잡 제어로 네트워크 과부하 방지",
    ],
    useCases: ["웹 브라우징(HTTP/HTTPS)", "파일 다운로드(FTP)", "이메일(SMTP)", "DB 쿼리 연결"],
    alternatives: ["UDP (빠른 비신뢰 전송)", "QUIC (UDP 기반 다중화)"],
    importanceKo: "웹에서 단 1글자의 데이터도 왜곡되거나 누락되지 않고 정확히 도달할 수 있는 이유가 바로 TCP 덕분입니다.",
  },
  {
    id: "udp",
    name: "UDP",
    fullName: "User Datagram Protocol",
    layer: 4,
    defaultPort: "N/A (L4)",
    transport: "UDP",
    rfc: "RFC 768",
    descriptionKo: "연결 수립 과정(Handshake) 없이 데이터를 독립적인 데이터그램 단위로 즉시 전송하는 가볍고 빠른 비연결성 프로토콜입니다.",
    keyPoints: [
      "헤더 크기가 8바이트로 극도로 작음 (TCP 헤더 20~60바이트 대비)",
      "재전송이나 순서 보장을 하지 않아 지연 시간(Latency)이 매우 짧음",
      "브로드캐스트(Broadcast) 및 멀티캐스트 지원",
    ],
    useCases: ["실시간 음성/영상 스트리밍(WebRTC, YouTube Live)", "온라인 FPS/MOBA 게임", "DNS 쿼리", "DHCP"],
    alternatives: ["TCP", "QUIC / HTTP/3", "RTP (Real-time Transport)"],
    importanceKo: "약간의 패킷 손실보다 실시간성(초저지연)이 더 중요한 서비스에서 필수적으로 사용됩니다.",
  },
  {
    id: "quic",
    name: "QUIC",
    fullName: "Quick UDP Internet Connections",
    layer: 4,
    defaultPort: "443 (UDP)",
    transport: "UDP",
    rfc: "RFC 9000",
    descriptionKo: "구글이 개발하고 IETF 표준화된 UDP 기반의 차세대 전송 프로토콜로, HTTP/3의 근간을 이룹니다.",
    keyPoints: [
      "TCP의 고질적 문제인 HoL (Head-of-Line) 블로킹 문제 해결",
      "연결 수립과 TLS 암호화를 단 0~1 RTT만에 완료하여 초기 로딩 속도 극대화",
      "Wi-Fi에서 LTE/5G로 네트워크 전환 시에도 끊김 없이 세션 유지(Connection ID)",
    ],
    useCases: ["HTTP/3 웹 서비스", "YouTube 및 대규모 CDN", "모바일 초고속 스트리밍"],
    alternatives: ["TCP + TLS", "WebTransport"],
    importanceKo: "모바일 네트워크 환경에서 웹 성능을 극대화하는 차세대 웹 표준 기술입니다.",
  },
  {
    id: "ip",
    name: "IPv4 / IPv6",
    fullName: "Internet Protocol",
    layer: 3,
    defaultPort: "N/A (L3)",
    transport: "N/A",
    rfc: "RFC 791 (IPv4) / RFC 8200 (IPv6)",
    descriptionKo: "호스트의 고유한 논리적 주소를 정의하고, 패킷을 전 세계 수많은 라우터를 거쳐 목적지까지 배송(Best-effort)하는 네트워크의 핵심 프로토콜입니다.",
    keyPoints: [
      "IPv4: 32비트 주소 체계 (약 43억 개, 고갈로 인해 사설 IP + NAT 사용)",
      "IPv6: 128비트 주소 체계 (거의 무한대의 IP 주소 공간 및 자동 설정 기능)",
      "비연결형 프로토콜이며 자체적인 전송 신뢰성(재전송)은 상위 TCP에 위임함",
    ],
    useCases: ["인터넷에 연결된 모든 기기 간의 데이터 패킷 라우팅", "서버 호스팅 IP", "클라우드 VPC"],
    alternatives: ["IPX (과거)", "AppleTalk (과거)"],
    importanceKo: "인터넷(Internet)이라는 거대한 글로벌 망이 존재할 수 있는 가장 핵심적인 주소 체계입니다.",
  },
  {
    id: "icmp",
    name: "ICMP",
    fullName: "Internet Control Message Protocol",
    layer: 3,
    defaultPort: "N/A (L3)",
    transport: "N/A",
    rfc: "RFC 792",
    descriptionKo: "네트워크 장치 간에 오류 상태를 보고하고 진단 메시지를 주고받기 위한 네트워크 계층 보조 프로토콜입니다.",
    keyPoints: [
      "포트 번호가 없으며 IP 패킷 페이로드에 직접 담겨 전달됨",
      "Echo Request(타입 8) / Echo Reply(타입 0)를 활용한 Ping 도구",
      "TTL 만료(타입 11) 메시지를 활용한 경로 추적(traceroute)",
    ],
    useCases: ["ping 명령어를 통한 서버 생존 확인", "traceroute 경로 추적", "MTU 크기 초과 오류 통보"],
    alternatives: ["TCP Ping", "HTTP 헬스체크"],
    importanceKo: "네트워크가 끊겼거나 서버가 응답하지 않을 때 가장 먼저 실행하는 진단 도구의 기반입니다.",
  },
  {
    id: "arp",
    name: "ARP",
    fullName: "Address Resolution Protocol",
    layer: 2,
    defaultPort: "N/A (L2)",
    transport: "N/A",
    rfc: "RFC 826",
    descriptionKo: "알고 있는 목적지 IP 주소를 기반으로, 로컬 네트워크(LAN) 내에서 실제 물리적 하드웨어 주소(MAC 주소)를 찾아내는 프로토콜입니다.",
    keyPoints: [
      "동일 네트워크에 '이 IP를 가진 사람 MAC 주소 알려줘!' 하고 브로드캐스트(FF:FF:FF:FF:FF:FF) 질문",
      "해당 IP를 가진 기기가 유니캐스트로 자신의 MAC 주소를 응답",
      "결과를 ARP 캐시 테이블에 저장하여 중복 질의 방지",
    ],
    useCases: ["공유기나 스위치에 연결된 컴퓨터가 패킷을 전송할 때 필수적으로 선행됨", "게이트웨이 MAC 주소 탐색"],
    alternatives: ["RARP (과거 역ARP)", "NDP (IPv6의 이웃 탐색 프로토콜)"],
    importanceKo: "L3의 논리적 IP 주소와 L2의 물리적 MAC 주소를 이어주는 필수 연결고리입니다.",
  },
  {
    id: "ethernet",
    name: "Ethernet (이더넷)",
    fullName: "IEEE 802.3 Ethernet Standard",
    layer: 2,
    defaultPort: "N/A (L2)",
    transport: "N/A",
    rfc: "IEEE 802.3",
    descriptionKo: "유선 로컬 영역 네트워크(LAN)에서 가장 널리 사용되는 데이터 링크 및 물리 표준 기술입니다.",
    keyPoints: [
      "48비트 MAC 주소(예: 00:1A:2B:3C:4D:5E)를 사용하여 프레임 목적지 식별",
      "프레임 끝에 4바이트 FCS(CRC-32) 트레일러를 붙여 전송 중 비트 오류 검출",
      "10Mbps부터 시작하여 현재 100Gbps, 400Gbps 초고속 이더넷까지 발전",
    ],
    useCases: ["사무실/가정 유선 랜 연결", "데이터센터 서버 랙 간 통신", "L2 스위칭"],
    alternatives: ["Wi-Fi (무선)", "Token Ring (과거)", "FDDI (과거)"],
    importanceKo: "우리가 컴퓨터나 공유기 뒤에 꽂는 랜선의 표준 규격입니다.",
  },
  {
    id: "dhcp",
    name: "DHCP",
    fullName: "Dynamic Host Configuration Protocol",
    layer: 7,
    defaultPort: "67 (Server) / 68 (Client)",
    transport: "UDP",
    rfc: "RFC 2131",
    descriptionKo: "네트워크에 접속한 기기에게 사용 가능한 IP 주소, 서브넷 마스크, 기본 게이트웨이, DNS 서버 정보를 자동으로 할당해 주는 프로토콜입니다.",
    keyPoints: [
      "DORA 4단계 과정: Discover(탐색) -> Offer(제안) -> Request(요청) -> Acknowledge(승인)",
      "사용자가 일일이 수동으로 IP를 입력할 필요 없이 랜선만 꽂거나 와이파이에 연결하면 즉시 인터넷 가능",
      "IP 주소 임대 시간(Lease Time) 관리를 통한 효율적인 주소 재사용",
    ],
    useCases: ["가정용 유무선 공유기의 자동 IP 할당", "사내 오피스 네트워크", "카페/공공 Wi-Fi"],
    alternatives: ["정적(Static) 고정 IP 수동 설정", "BOOTP (과거)"],
    importanceKo: "비전문가도 누구나 와이파이 비번만 치면 인터넷을 바로 쓸 수 있게 만들어준 마법 같은 프로토콜입니다.",
  },
  {
    id: "ssh",
    name: "SSH",
    fullName: "Secure Shell",
    layer: 7,
    defaultPort: "22",
    transport: "TCP",
    rfc: "RFC 4253",
    descriptionKo: "원격 서버에 안전하게 접속하여 명령어를 실행하고 파일을 제어할 수 있도록 해주는 강력한 암호화 프로토콜입니다.",
    keyPoints: [
      "과거 평문으로 비밀번호를 전송하던 Telnet, rlogin을 완전히 대체",
      "비대칭키(공개키/개인키 쌍) 기반의 안전한 키 인증 지원",
      "포트 포워딩(SSH 터널링)을 통해 방화벽 내부 서비스에 안전하게 접근 가능",
    ],
    useCases: ["AWS EC2, 리눅스 원격 서버 관리", "Git 커밋 푸시(git@github.com)", "SCP / SFTP 파일 전송"],
    alternatives: ["Telnet (비보안, 폐기)", "Mosh (모바일 셸)", "AWS Systems Manager"],
    importanceKo: "백엔드 개발자 및 데브옵스 엔지니어가 클라우드 서버를 제어할 때 가장 많이 쓰는 프로토콜입니다.",
  },
];
