import { SimulationStep, HeaderBlock, PacketPreset } from "@/types";
import { stringToBinary } from "@/lib/utils";

export const PRESET_PACKETS: PacketPreset[] = [
  {
    id: "http-web",
    label: "🌐 웹 페이지 요청 (HTTP GET)",
    protocol: "HTTP",
    message: "GET /index.html HTTP/1.1\r\nHost: my-shop.com",
    srcPort: 54321,
    dstPort: 80,
    srcIp: "192.168.1.15",
    dstIp: "93.184.216.34",
    srcMac: "00:1A:2B:AA:BB:CC",
    dstMac: "CC:DD:EE:11:22:33",
  },
  {
    id: "https-login",
    label: "🔐 보안 로그인 요청 (HTTPS POST)",
    protocol: "HTTPS",
    message: "POST /api/login HTTP/1.1 { id: 'sungwon', pw: '***' }",
    srcPort: 58900,
    dstPort: 443,
    srcIp: "192.168.1.15",
    dstIp: "104.244.42.1",
    srcMac: "00:1A:2B:AA:BB:CC",
    dstMac: "CC:DD:EE:11:22:33",
  },
  {
    id: "dns-lookup",
    label: "🔎 도메인 주소 조회 (DNS Query)",
    protocol: "DNS",
    message: "DNS Query: A google.com (Transaction ID: 0x4f2a)",
    srcPort: 60123,
    dstPort: 53,
    srcIp: "192.168.1.15",
    dstIp: "8.8.8.8",
    srcMac: "00:1A:2B:AA:BB:CC",
    dstMac: "CC:DD:EE:11:22:33",
  },
  {
    id: "custom-msg",
    label: "💬 자유 메시지 전송",
    protocol: "CUSTOM",
    message: "안녕하세요! OSI 7계층 시뮬레이터 테스트입니다 🚀",
    srcPort: 51234,
    dstPort: 8080,
    srcIp: "192.168.0.10",
    dstIp: "192.168.0.20",
    srcMac: "AA:11:22:33:44:55",
    dstMac: "BB:66:77:88:99:00",
  },
];

export function generateSimulationSteps(config: PacketPreset): SimulationStep[] {
  const binarySnippet = stringToBinary(config.message.slice(0, 10)) + "...";

  const l7Header: HeaderBlock = {
    layer: 7,
    name: "응용 페이로드",
    tag: "L7: DATA",
    color: "#EF4444",
    content: `${config.protocol} Payload (${config.message.slice(0, 20)}...)`,
  };

  const l6Header: HeaderBlock = {
    layer: 6,
    name: "표현 포맷/암호화",
    tag: "L6: TLS/UTF8",
    color: "#F97316",
    content: config.protocol === "HTTPS" ? "TLS 1.3 Ciphertext" : "UTF-8 Formatted",
  };

  const l5Header: HeaderBlock = {
    layer: 5,
    name: "세션 동기화",
    tag: "L5: SESS",
    color: "#F59E0B",
    content: "Session_ID: #89AC31",
  };

  const l4Header: HeaderBlock = {
    layer: 4,
    name: "전송 계층 헤더",
    tag: `L4: ${config.protocol === "DNS" ? "UDP" : "TCP"}`,
    color: "#10B981",
    content: `Port: ${config.srcPort} ➔ ${config.dstPort}`,
  };

  const l3Header: HeaderBlock = {
    layer: 3,
    name: "네트워크 계층 헤더",
    tag: "L3: IPv4",
    color: "#06B6D4",
    content: `IP: ${config.srcIp} ➔ ${config.dstIp}`,
  };

  const l2Header: HeaderBlock = {
    layer: 2,
    name: "이더넷 헤더",
    tag: "L2: ETH",
    color: "#3B82F6",
    content: `MAC: ${config.srcMac} ➔ ${config.dstMac}`,
  };

  const l2Trailer: HeaderBlock = {
    layer: 2,
    name: "FCS 체크섬 트레일러",
    tag: "L2: FCS",
    color: "#3B82F6",
    content: "CRC-32 Checksum (0x9B42A1)",
    isTrailer: true,
  };

  return [
    {
      stepIndex: 0,
      totalSteps: 15,
      stage: "IDLE",
      layerNumber: 0,
      layerName: "전송 대기 중",
      actor: "sender",
      title: "준비 완료: 메시지 전송 시작",
      actionText: "송신 장비(클라이언트)가 사용자로부터 전송할 메시지를 입력받았습니다.",
      detailDescription: `사용자 메시지: "${config.message}"\n프로토콜: ${config.protocol} (목적지 포트: ${config.dstPort})`,
      currentHeaders: [],
      payloadText: config.message,
    },
    {
      stepIndex: 1,
      totalSteps: 15,
      stage: "SENDER_ENCAP",
      layerNumber: 7,
      layerName: "7계층 - 응용 계층 (Application)",
      actor: "sender",
      title: "[송신측] L7 응용 계층: 데이터 생성",
      actionText: `클라이언트 웹 브라우저가 ${config.protocol} 요청 메시지 데이터를 구성했습니다.`,
      detailDescription: "사용자가 작성한 메시지가 네트워크 전송을 위한 표준 응용 프로토콜 페이로드로 변환됩니다.",
      currentHeaders: [l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 2,
      totalSteps: 15,
      stage: "SENDER_ENCAP",
      layerNumber: 6,
      layerName: "6계층 - 표현 계층 (Presentation)",
      actor: "sender",
      title: "[송신측] L6 표현 계층: 데이터 인코딩 및 암호화",
      actionText: config.protocol === "HTTPS" 
        ? "TLS 1.3 암호화가 적용되어 페이로드가 안전하게 잠겼습니다."
        : "텍스트가 UTF-8 표준 문자 인코딩으로 변환되었습니다.",
      detailDescription: "수신자가 동일하게 해석할 수 있도록 데이터 형식을 표준화하고 보안을 위해 암호화합니다.",
      currentHeaders: [l6Header, l7Header],
      payloadText: config.protocol === "HTTPS" ? "[암호화된 바이너리 블록]" : config.message,
    },
    {
      stepIndex: 3,
      totalSteps: 15,
      stage: "SENDER_ENCAP",
      layerNumber: 5,
      layerName: "5계층 - 세션 계층 (Session)",
      actor: "sender",
      title: "[송신측] L5 세션 계층: 세션 관리 및 식별자 부착",
      actionText: "송수신 장치 간의 논리적 통신 세션 토큰과 동기화 지점을 부여했습니다.",
      detailDescription: "통신 도중 연결이 끊기더라도 복구할 수 있도록 세션 식별자와 체크포인트를 관리합니다.",
      currentHeaders: [l5Header, l6Header, l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 4,
      totalSteps: 15,
      stage: "SENDER_ENCAP",
      layerNumber: 4,
      layerName: "4계층 - 전송 계층 (Transport)",
      actor: "sender",
      title: "[송신측] L4 전송 계층: 포트(Port) 헤더 부착 ➔ Segment 생성",
      actionText: `출발지 포트(${config.srcPort})와 도착지 포트(${config.dstPort}) 헤더를 붙여 세그먼트를 완성했습니다.`,
      detailDescription: `PDU가 'Data'에서 'Segment'로 승격되었습니다. 수신 측 서버의 어떤 프로세스(예: ${config.dstPort}번 웹서버)가 이 패킷을 수령할지 결정됩니다.`,
      currentHeaders: [l4Header, l5Header, l6Header, l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 5,
      totalSteps: 15,
      stage: "SENDER_ENCAP",
      layerNumber: 3,
      layerName: "3계층 - 네트워크 계층 (Network)",
      actor: "sender",
      title: "[송신측] L3 네트워크 계층: IP 헤더 부착 ➔ Packet 생성",
      actionText: `출발지 IP(${config.srcIp})와 목적지 IP(${config.dstIp}) 헤더를 추가했습니다.`,
      detailDescription: "PDU가 'Packet'으로 포장되었습니다. 전 세계 라우터들이 이 IP 주소를 보고 목적지 서버까지의 최적 경로(Routing)를 계산합니다.",
      currentHeaders: [l3Header, l4Header, l5Header, l6Header, l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 6,
      totalSteps: 15,
      stage: "SENDER_ENCAP",
      layerNumber: 2,
      layerName: "2계층 - 데이터 링크 계층 (Data Link)",
      actor: "sender",
      title: "[송신측] L2 데이터 링크: 이더넷 헤더 & FCS 트레일러 부착 ➔ Frame 생성",
      actionText: `출발지 MAC(${config.srcMac}), 목적지 MAC(${config.dstMac}) 헤더와 CRC 오류검출 트레일러를 붙였습니다.`,
      detailDescription: "PDU가 'Frame'으로 최종 완성되었습니다. 앞에는 MAC 주소 헤더가, 뒤에는 전송 중 깨짐을 감지할 FCS 트레일러가 붙어 데이터가 완벽히 포장되었습니다.",
      currentHeaders: [l2Header, l3Header, l4Header, l5Header, l6Header, l7Header, l2Trailer],
      payloadText: config.message,
    },
    {
      stepIndex: 7,
      totalSteps: 15,
      stage: "SENDER_ENCAP",
      layerNumber: 1,
      layerName: "1계층 - 물리 계층 (Physical)",
      actor: "sender",
      title: "[송신측] L1 물리 계층: 프레임을 0과 1의 전기/광 신호로 변환",
      actionText: "네트워크 카드(NIC)가 완성된 프레임을 2진수 비트열(Bitstream) 전기 신호로 인코딩했습니다.",
      detailDescription: "01001000 01100101... 형태의 전압 펄스로 변환되어 구리 케이블 또는 무선 안테나로 흘려보낼 준비를 마쳤습니다.",
      currentHeaders: [l2Header, l3Header, l4Header, l5Header, l6Header, l7Header, l2Trailer],
      payloadText: config.message,
      bitsSnippet: binarySnippet,
    },
    {
      stepIndex: 8,
      totalSteps: 15,
      stage: "PHYSICAL_TRANSIT",
      layerNumber: 1,
      layerName: "물리적 전송선로 (Transmission Medium)",
      actor: "cable",
      title: "[전송 중] 케이블 및 인터넷 백본망을 통한 비트 이동 ⚡",
      actionText: "광케이블과 라우터 망을 통해 0과 1의 빛/전기 신호가 수신지 서버로 빛의 속도로 이동하고 있습니다.",
      detailDescription: "중간 라우터와 스위치들을 거치며 물리적 신호가 목적지 서버의 네트워크 인터페이스 카드(NIC)에 도달합니다.",
      currentHeaders: [l2Header, l3Header, l4Header, l5Header, l6Header, l7Header, l2Trailer],
      payloadText: "[신호 전송 중...]",
      bitsSnippet: binarySnippet,
    },
    {
      stepIndex: 9,
      totalSteps: 15,
      stage: "RECEIVER_DECAP",
      layerNumber: 1,
      layerName: "1계층 - 물리 계층 (Physical)",
      actor: "receiver",
      title: "[수신측] L1 물리 계층: 전기 신호 수신 및 프레임 복원",
      actionText: "수신 서버의 랜카드(NIC)가 전압 신호를 감지하여 2진수 비트열 프레임으로 재조합했습니다.",
      detailDescription: "수신된 0과 1의 신호가 상위 2계층 데이터 링크로 전달됩니다.",
      currentHeaders: [l2Header, l3Header, l4Header, l5Header, l6Header, l7Header, l2Trailer],
      payloadText: config.message,
      bitsSnippet: binarySnippet,
    },
    {
      stepIndex: 10,
      totalSteps: 15,
      stage: "RECEIVER_DECAP",
      layerNumber: 2,
      layerName: "2계층 - 데이터 링크 계층 (Data Link)",
      actor: "receiver",
      title: "[수신측] L2 데이터 링크: MAC 검증 및 FCS 무결성 확인 ➔ 역캡슐화",
      actionText: `목적지 MAC 주소(${config.dstMac})가 내 장비의 주소와 일치함을 확인하고 FCS 오류가 없음을 검증한 뒤 L2 헤더를 벗겨냈습니다.`,
      detailDescription: "이더넷 헤더와 트레일러가 제거되어 순수한 IP 패킷(Packet)만 남았습니다. 상위 네트워크 계층으로 넘깁니다.",
      currentHeaders: [l3Header, l4Header, l5Header, l6Header, l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 11,
      totalSteps: 15,
      stage: "RECEIVER_DECAP",
      layerNumber: 3,
      layerName: "3계층 - 네트워크 계층 (Network)",
      actor: "receiver",
      title: "[수신측] L3 네트워크 계층: IP 주소 확인 ➔ IP 헤더 제거",
      actionText: `패킷의 목적지 IP(${config.dstIp})가 본 서버의 IP 주소와 일치함을 확인하고 IP 헤더를 벗겨냈습니다.`,
      detailDescription: "IP 헤더가 해체되고 전송 계층 세그먼트(Segment)가 드러났습니다. 프로토콜 필드를 보고 TCP/UDP 모듈로 인계합니다.",
      currentHeaders: [l4Header, l5Header, l6Header, l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 12,
      totalSteps: 15,
      stage: "RECEIVER_DECAP",
      layerNumber: 4,
      layerName: "4계층 - 전송 계층 (Transport)",
      actor: "receiver",
      title: "[수신측] L4 전송 계층: 포트(${config.dstPort}) 확인 ➔ 프로세스 전달 및 헤더 제거",
      actionText: `도착지 포트 번호(${config.dstPort})를 확인하고 해당 포트를 열고 대기 중인 응용 서비스에게 데이터를 넘기며 TCP/UDP 헤더를 벗겨냈습니다.`,
      detailDescription: "시퀀스 번호 검증과 수신 확인(ACK) 처리가 완료되었으며, 순수 데이터(Data) 상태로 복원되었습니다.",
      currentHeaders: [l5Header, l6Header, l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 13,
      totalSteps: 15,
      stage: "RECEIVER_DECAP",
      layerNumber: 5,
      layerName: "5·6계층 - 세션 및 표현 계층 (Session & Presentation)",
      actor: "receiver",
      title: "[수신측] L5/L6 계층: 세션 확인, 복호화 및 UTF-8 디코딩",
      actionText: config.protocol === "HTTPS"
        ? "서버의 개인키로 TLS 암호문을 안전하게 복호화(Decryption)하여 원본 텍스트를 복원했습니다."
        : "바이너리 데이터를 UTF-8 텍스트로 디코딩하고 세션을 매핑했습니다.",
      detailDescription: "포장 상자가 모두 벗겨지고 원래 보냈던 메시지가 완벽히 복원되었습니다.",
      currentHeaders: [l7Header],
      payloadText: config.message,
    },
    {
      stepIndex: 14,
      totalSteps: 15,
      stage: "COMPLETED",
      layerNumber: 7,
      layerName: "7계층 - 응용 계층 (Application)",
      actor: "receiver",
      title: "🎉 [전송 완료] 수신지 서버 애플리케이션에 메시지 도달!",
      actionText: `서버 프로그램(포트 ${config.dstPort})이 클라이언트의 "${config.protocol}" 요청을 성공적으로 수신하여 처리를 시작했습니다.`,
      detailDescription: `[최종 수신 메시지]: "${config.message}"\nOSI 7계층을 거치며 캡슐화 ➔ 물리 전송 ➔ 역캡슐화의 전 과정이 성공적으로 완료되었습니다!`,
      currentHeaders: [],
      payloadText: config.message,
    },
  ];
}
