import { QuizItem } from "@/types";

export const NETWORK_QUIZ_DATA: QuizItem[] = [
  {
    id: 1,
    layerNumber: 4,
    question: "웹 브라우저에서 'http://localhost:3000'으로 접속할 때, 숫자 '3000'은 OSI 7계층 중 어느 계층의 주소 정보일까요?",
    options: [
      "2계층 (데이터 링크 계층 - MAC 주소)",
      "3계층 (네트워크 계층 - IP 주소)",
      "4계층 (전송 계층 - 포트 번호)",
      "7계층 (응용 계층 - URL 경로)",
    ],
    answer: 2,
    explanation: "3000은 특정 프로그램(프로세스)을 식별하기 위한 '포트(Port) 번호'로, OSI 4계층(전송 계층)에서 TCP/UDP 헤더에 포함됩니다.",
    practicalTip: "서버 개발 시 EADDRINUSE 오류는 이미 다른 프로그램이 해당 4계층 포트를 점유하고 있을 때 발생합니다.",
  },
  {
    id: 2,
    layerNumber: 3,
    question: "터미널에서 'ping google.com' 명령을 실행하여 서버의 응답 속도를 측정할 때 사용되는 프로토콜은 무엇일까요?",
    options: ["HTTP", "ICMP", "ARP", "BGP"],
    answer: 1,
    explanation: "Ping은 OSI 3계층(네트워크 계층)의 진단용 프로토콜인 ICMP(Internet Control Message Protocol)의 Echo Request/Reply 메시지를 사용합니다.",
    practicalTip: "ICMP는 포트 번호(L4)가 없는 L3 프로토콜입니다.",
  },
  {
    id: 3,
    layerNumber: 2,
    question: "동일한 Wi-Fi 공유기(LAN)에 연결된 컴퓨터 간에 통신할 때, 실제 하드웨어를 식별하기 위해 사용되는 고유 물리 주소는 무엇일까요?",
    options: ["IP 주소", "MAC 주소", "포트 번호", "도메인 네임"],
    answer: 1,
    explanation: "LAN 내에서 장비를 구별하는 고유 하드웨어 주소는 2계층의 MAC(Media Access Control) 주소입니다. (예: 00:1A:2B:3C:4D:5E)",
    practicalTip: "IP 주소만 알고 있을 때 상대방의 MAC 주소를 알아내는 프로토콜이 바로 ARP입니다.",
  },
  {
    id: 4,
    layerNumber: 6,
    question: "HTTPS 웹사이트에 접속할 때 브라우저와 서버 간의 데이터를 암호화(TLS/SSL)하고 압축하는 계층은 어디일까요?",
    options: [
      "7계층 (응용 계층)",
      "6계층 (표현 계층)",
      "4계층 (전송 계층)",
      "1계층 (물리 계층)",
    ],
    answer: 1,
    explanation: "데이터의 암호화(Encryption), 압축(Compression), 문자 인코딩 변환(UTF-8 등)은 OSI 6계층(표현 계층)의 고유 역할입니다.",
    practicalTip: "TCP/IP 4계층 모델에서는 5, 6, 7계층이 '응용 계층(Application)' 하나로 묶여 있습니다.",
  },
  {
    id: 5,
    layerNumber: 4,
    question: "유튜브 라이브 스트리밍이나 실시간 FPS 온라인 게임처럼 '약간의 손실이 있더라도 지연 시간(초저지연)이 가장 중요한' 서비스에 적합한 전송 프로토콜은?",
    options: ["TCP", "UDP", "HTTP/1.1", "FTP"],
    answer: 1,
    explanation: "UDP는 3-Way Handshake나 재전송 확인 과정이 없어 오버헤드가 극히 적고 지연 시간이 짧기 때문에 실시간 스트리밍 및 게임에 최적입니다.",
    practicalTip: "반면 1글자도 틀리면 안 되는 금융 거래나 웹 서핑(HTML)은 신뢰성 있는 TCP를 사용합니다.",
  },
  {
    id: 6,
    layerNumber: 7,
    question: "인터넷 주소창에 'https://www.google.com'을 입력했을 때, 이 도메인을 실제 IP 주소(142.250.196.110)로 찾아주는 시스템은?",
    options: ["DHCP", "DNS", "NAT", "BGP"],
    answer: 1,
    explanation: "DNS(Domain Name System)는 인간 친화적인 도메인 네임을 컴퓨터가 이해할 수 있는 IP 주소로 변환해 주는 인터넷의 전화번호부입니다.",
    practicalTip: "DNS 쿼리는 보통 빠른 응답을 위해 UDP 53번 포트를 사용합니다.",
  },
  {
    id: 7,
    layerNumber: 1,
    question: "OSI 1계층(물리 계층)의 데이터 전송 단위(PDU)는 무엇일까요?",
    options: ["Frame (프레임)", "Packet (패킷)", "Segment (세그먼트)", "Bits (비트)"],
    answer: 3,
    explanation: "물리 계층(1계층)은 데이터를 0과 1의 전기 신호, 빛 펄스 등의 'Bits(비트)' 단위로 케이블이나 전파를 통해 전송합니다.",
    practicalTip: "계층별 PDU: 7~5계층(Data) ➔ 4계층(Segment) ➔ 3계층(Packet) ➔ 2계층(Frame) ➔ 1계층(Bits).",
  },
  {
    id: 8,
    layerNumber: 3,
    question: "전 세계 수억 대의 컴퓨터 중 목적지 컴퓨터까지 가는 최적의 경로(고속도로)를 찾아주는 장비(Hardware)는 무엇일까요?",
    options: ["허브 (Hub)", "L2 스위치 (Switch)", "라우터 (Router)", "리피터 (Repeater)"],
    answer: 2,
    explanation: "라우터(Router)는 3계층(네트워크 계층) 장비로, IP 주소를 기반으로 라우팅 테이블을 참조하여 목적지까지의 최적 경로를 찾아 패킷을 중계합니다.",
    practicalTip: "집에서 사용하는 유무선 공유기는 '라우터 + L2 스위치 + Wi-Fi AP + NAT + DHCP 서버'가 하나로 합쳐진 복합 장비입니다.",
  },
];
